version: '3.9'

services:
  app:
    build:
      context: .
    comand: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes: 
    - ./EcoBack:/EcoBack
    ports: 
    - 8000:8000
    environment:
      - DJANGO_DEBUG=1
 