version: '3.9'

services:
  ecoback:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - ./EcoBack/db.sqlite3:/usr/src/app/db.sqlite3
      - ./EcoBack:/EcoBack
    ports: 
      - 8000:8000
    environment:
      - DJANGO_DEBUG=1
