version: "3.9"

services:
  ecoback:  # 서비스 이름을 소문자로 변경
    build:
      context: .
    restart: always
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS="${DOMAIN},www.${DOMAIN}"


  proxy:
    build:
      context: ./docker/proxy
    restart: always
    depends_on:
      - ecoback  # 서비스 이름을 소문자로 변경
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN="${DOMAIN},www.${DOMAIN}"

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    environment:
      - EMAIL=${ACME_DEFAULT_EMAIL}
      - DOMAIN="${DOMAIN},www.${DOMAIN}"
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
  